services:
  api:
    image: python:3.11-slim
    working_dir: /srv
    volumes: [ "../..:/srv" ]
    command: sh -lc "python -m pip install -r apps/api/requirements.txt || true; uvicorn apps.api.app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports: [ "8000:8000" ]
    environment:
      - PYTHONPATH=/srv/apps/api
      - MINIO_ENDPOINT=minio:9000
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/processlab
    depends_on: [ db, minio ]
  web:
    image: node:20
    working_dir: /srv/apps/web
    volumes:
      - "../..:/srv"
      # O TRUQUE: Cria volumes anônimos para isolar as dependências do container
      - "/srv/node_modules"
      - "/srv/apps/web/node_modules"
    # Adicionamos --force para garantir que ele não peça confirmação
    command: sh -lc "npm install -g pnpm && pnpm install --force && pnpm dev --port 3004 --hostname 0.0.0.0"
    ports: [ "3004:3004" ]
    depends_on: [ api ]
  worker:
    image: python:3.11-slim
    command: [ "sh", "-lc", "echo worker-stub && sleep 3d" ]
    volumes: [ "../..:/srv" ]
    depends_on: [ db, minio ]
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: processlab
    ports: [ "5433:5432" ]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: [ "9000:9000", "9001:9001" ]
    volumes: [ "minio-data:/data" ]
volumes:
  minio-data:
